In [1]:
import pandas as pd
import yfinance as yf
gold_data = pd.read_csv("goldprices.csv")

In [2]:
gold_data.describe()

,Open,High,Low,Close,Adj Close,Volume
count,5205.000000,5205.000000,5205.000000,5205.000000,5205.000000,5205.000000
mean,1018.675312,1023.820096,1013.118867,1018.535524,1018.535524,4257.242651
std,490.316244,493.277232,486.969047,490.177751,490.177751,24536.337729
min,255.000000,256.100006,255.000000,255.100006,255.100006,0.000000
25%,485.600006,486.000000,486.000000,489.000000,489.000000,18.000000
50%,1174.599976,1180.300049,1168.300049,1174.599976,1174.599976,95.000000
75%,1334.500000,1341.400024,1326.900024,1335.099976,1335.099976,357.000000
max,2045.500000,2063.000000,2040.000000,2051.500000,2051.500000,386334.000000

In [3]:
gold_data.head()

,Date,Open,High,Low,Close,Adj Close,Volume
0,2000-08-30,273.899994,273.899994,273.899994,273.899994,273.899994,0.0
1,2000-08-31,274.799988,278.299988,274.799988,278.299988,278.299988,0.0
2,2000-09-01,277.000000,277.000000,277.000000,277.000000,277.000000,0.0
3,2000-09-04,NaN,NaN,NaN,NaN,NaN,NaN
4,2000-09-05,275.799988,275.799988,275.799988,275.799988,275.799988,2.0

In [25]:
tickers = {
    "Gold_YF": "GC=F",
    "DXY": "DX-Y.NYB",
    "TNX": "^TNX",
    "VIX": "^VIX",
    "CrdOil": "CL=F",
    "Cu": "HG=F",
    "Ag": "SI=F",
    "NatGas": "NG=F",
    "Corn": "ZC=F",
    "Soya": "ZS=F",
    "Cattle": "LE=F",
    "Coco": "CC=F",
    "Coffee": "KC=F",
    "Cotton": "CT=F"    
}

data = {}

for name, ticker in tickers.items():
    df = yf.download(ticker, start="2000-08-30", interval="1d") #2000-08-30 is where gold YF starts from
    df = df[["Close"]]
    df.rename(columns={"Close": name}, inplace=True)
    data[name] = df

C:\Users\Sanket Lalwani\AppData\Local\Temp\ipykernel_13728\4054550317.py:21: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2000-08-30", interval="1d") #2000-08-30 is where gold YF starts from
[*********************100%***********************]  1 of 1 completed
C:\Users\Sanket Lalwani\AppData\Local\Temp\ipykernel_13728\4054550317.py:21: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2000-08-30", interval="1d") #2000-08-30 is where gold YF starts from
[*********************100%***********************]  1 of 1 completed
C:\Users\Sanket Lalwani\AppData\Local\Temp\ipykernel_13728\4054550317.py:21: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2000-08-30", interval="1d") #2000-08-30 is where gold YF starts from
[*********************100%***********************]  1 of 1 completed
C:\Users\Sanket Lalwani\AppData\Local\Temp\ipykernel_13728\4054550317.py:21: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2000-08-30", interval="1d") #2000-08-30 is where gold YF starts from
[*********************100%***********************]  1 of 1 completed
C:\Users\Sanket Lalwani\AppData\Local\Temp\ipykernel_13728\4054550317.py:21: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2000-08-30", interval="1d") #2000-08-30 is where gold YF starts from
[*********************100%***********************]  1 of 1 completed
C:\Users\Sanket Lalwani\AppData\Local\Temp\ipykernel_13728\4054550317.py:21: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2000-08-30", interval="1d") #2000-08-30 is where gold YF starts from
[*********************100%***********************]  1 of 1 completed
C:\Users\Sanket Lalwani\AppData\Local\Temp\ipykernel_13728\4054550317.py:21: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2000-08-30", interval="1d") #2000-08-30 is where gold YF starts from
[*********************100%***********************]  1 of 1 completed
C:\Users\Sanket Lalwani\AppData\Local\Temp\ipykernel_13728\4054550317.py:21: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2000-08-30", interval="1d") #2000-08-30 is where gold YF starts from
[*********************100%***********************]  1 of 1 completed
C:\Users\Sanket Lalwani\AppData\Local\Temp\ipykernel_13728\4054550317.py:21: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2000-08-30", interval="1d") #2000-08-30 is where gold YF starts from
[*********************100%***********************]  1 of 1 completed
C:\Users\Sanket Lalwani\AppData\Local\Temp\ipykernel_13728\4054550317.py:21: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2000-08-30", interval="1d") #2000-08-30 is where gold YF starts from
[*********************100%***********************]  1 of 1 completed
C:\Users\Sanket Lalwani\AppData\Local\Temp\ipykernel_13728\4054550317.py:21: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2000-08-30", interval="1d") #2000-08-30 is where gold YF starts from
[*********************100%***********************]  1 of 1 completed
C:\Users\Sanket Lalwani\AppData\Local\Temp\ipykernel_13728\4054550317.py:21: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2000-08-30", interval="1d") #2000-08-30 is where gold YF starts from
[*********************100%***********************]  1 of 1 completed
C:\Users\Sanket Lalwani\AppData\Local\Temp\ipykernel_13728\4054550317.py:21: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2000-08-30", interval="1d") #2000-08-30 is where gold YF starts from
[*********************100%***********************]  1 of 1 completed
C:\Users\Sanket Lalwani\AppData\Local\Temp\ipykernel_13728\4054550317.py:21: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(ticker, start="2000-08-30", interval="1d") #2000-08-30 is where gold YF starts from
[*********************100%***********************]  1 of 1 completed

In [26]:
merged_df = pd.concat(data.values(), axis=1)
merged_df.columns = merged_df.columns.get_level_values(0)

In [27]:
merged_df.reset_index(inplace=True) 
merged_df.columns.name = "Index"

In [28]:
# Calculating the Exceptional VIX values ranging above the std deviation where 0 = mean, -1 = -1*sigma, +1 = 1*sigma and so on...
mean_vix = merged_df['VIX'].mean()
std_vix = merged_df['VIX'].std()

merged_df['VIX_PCE'] = ((merged_df['VIX'] - mean_vix) / std_vix)

merged_df

Index,Date,Gold_YF,DXY,TNX,VIX,CrdOil,Cu,Ag,NatGas,Corn,Soya,Cattle,Coco,Coffee,Cotton,VIX_PCE
0,2000-08-30,273.899994,112.139999,5.800,17.690001,33.400002,0.8850,4.930000,4.805,181.50,NaN,NaN,760.0,73.900002,64.750000,-0.244654
1,2000-08-31,278.299988,112.599998,5.729,16.840000,33.099998,0.8850,5.003000,4.780,182.00,NaN,NaN,745.0,74.500000,63.369999,-0.345588
2,2000-09-01,277.000000,111.419998,5.675,17.530001,33.380001,0.8890,5.004000,4.835,183.25,NaN,NaN,757.0,75.000000,63.490002,-0.263653
3,2000-09-05,275.799988,112.410004,5.683,19.820000,33.799999,0.9060,4.998000,4.960,183.50,NaN,NaN,775.0,73.099998,64.540001,0.008273
4,2000-09-06,274.200012,114.120003,5.712,20.790001,34.950001,0.9015,4.983000,5.065,186.25,NaN,NaN,780.0,75.250000,64.360001,0.123456
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6449,2026-03-02,5294.399902,98.379997,4.048,21.440001,71.230003,5.8945,88.283997,2.960,433.25,1150.00,233.100006,2931.0,288.350006,62.590000,0.200640
6450,2026-03-03,5107.399902,99.050003,4.056,23.570000,74.559998,5.7735,82.922997,3.054,434.25,1155.75,234.125000,2925.0,286.950012,62.040001,0.453567
6451,2026-03-04,5120.200195,98.769997,4.080,21.150000,74.660004,5.8550,82.633003,2.917,431.75,1154.50,238.350006,2968.0,290.700012,62.160000,0.166204
6452,2026-03-05,5065.299805,99.320000,4.146,23.750000,81.010002,5.7530,81.686996,3.003,441.50,1163.75,238.524994,2963.0,293.000000,63.029999,0.474941
6453,2026-03-06,5158.700195,98.855003,4.133,29.490000,90.900002,5.8070,84.310997,3.186,460.50,1200.75,234.574997,3138.0,297.600006,64.300003,1.156538

In [29]:
merged_df.to_csv("gold_macro_yfinance_2000.csv")

In [30]:
gold_data["Date"] = pd.to_datetime(gold_data["Date"])
merged_df["Date"] = pd.to_datetime(merged_df["Date"])

In [31]:
gold_merged = pd.merge(gold_data, merged_df, on="Date", how="inner")

In [32]:
gold_merged[["Date", "Close", "Gold_YF"]]

           Date        Close      Gold_YF
0    2000-08-30   273.899994   273.899994
1    2000-08-31   278.299988   278.299988
2    2000-09-01   277.000000   277.000000
3    2000-09-05   275.799988   275.799988
4    2000-09-06   274.200012   274.200012
...         ...          ...          ...
5279 2021-07-12  1805.500000  1805.500000
5280 2021-07-13  1809.400024  1809.400024
5281 2021-07-14  1824.300049  1824.300049
5282 2021-07-15  1828.400024  1828.400024
5283 2021-07-16  1814.500000  1814.500000

[5284 rows x 3 columns]

In [33]:
merged_df.describe()

Index,Date,Gold_YF,DXY,TNX,VIX,CrdOil,Cu,Ag,NatGas,Corn,Soya,Cattle,Coco,Coffee,Cotton,VIX_PCE
count,6454,6402.000000,6442.000000,6410.000000,6416.000000,6406.000000,6407.000000,6404.000000,6408.000000,6382.000000,6406.000000,6269.000000,6398.000000,6396.000000,6398.000000,6.416000e+03
mean,2013-05-18 09:57:03.737217280,1276.718181,92.543065,3.241407,19.750332,64.685738,2.864362,18.428019,4.390791,413.177922,1007.931158,118.147555,2774.805877,145.183271,71.827420,2.480698e-16
min,2000-08-30 00:00:00,255.100006,71.330002,0.499000,9.140000,-37.630001,0.604000,4.026000,1.482000,181.000000,418.500000,59.400002,674.000000,41.500000,28.520000,-1.259925e+00
25%,2006-12-18 06:00:00,651.849991,82.552502,2.217000,13.940000,46.462500,2.142000,12.222250,2.801000,321.250000,821.500000,89.750000,1894.000000,104.099998,57.469999,-6.899486e-01
50%,2013-05-14 12:00:00,1251.200012,93.050003,3.356000,17.585000,63.669998,3.050500,17.023500,3.745000,379.500000,989.500000,112.474998,2425.000000,127.150002,67.769997,-2.571226e-01
75%,2019-10-08 18:00:00,1696.325012,99.519997,4.247750,23.030001,81.795002,3.701750,23.668499,5.485750,493.000000,1279.000000,133.250000,2928.750000,176.174995,81.965000,3.894446e-01
max,2026-03-06 00:00:00,5318.399902,120.900002,5.892000,82.690002,145.289993,6.175500,115.080002,15.378000,831.250000,1771.000000,247.500000,12565.000000,438.899994,215.149994,7.473778e+00
std,NaN,787.125435,11.165467,1.217772,8.421399,24.500017,1.194634,11.189315,2.199545,156.092739,324.543967,37.634010,1790.758135,72.002700,24.298929,1.000000e+00

In [34]:
merged_df.isna().sum()

Index
Date         0
Gold_YF     52
DXY         12
TNX         44
VIX         38
CrdOil      48
Cu          47
Ag          50
NatGas      46
Corn        72
Soya        48
Cattle     185
Coco        56
Coffee      58
Cotton      56
VIX_PCE     38
dtype: int64

In [35]:
merged_df[merged_df.isna().any(axis=1)]
merged_df = merged_df.bfill()
merged_df

Index,Date,Gold_YF,DXY,TNX,VIX,CrdOil,Cu,Ag,NatGas,Corn,Soya,Cattle,Coco,Coffee,Cotton,VIX_PCE
0,2000-08-30,273.899994,112.139999,5.800,17.690001,33.400002,0.8850,4.930000,4.805,181.50,493.75,77.750000,760.0,73.900002,64.750000,-0.244654
1,2000-08-31,278.299988,112.599998,5.729,16.840000,33.099998,0.8850,5.003000,4.780,182.00,493.75,77.750000,745.0,74.500000,63.369999,-0.345588
2,2000-09-01,277.000000,111.419998,5.675,17.530001,33.380001,0.8890,5.004000,4.835,183.25,493.75,77.750000,757.0,75.000000,63.490002,-0.263653
3,2000-09-05,275.799988,112.410004,5.683,19.820000,33.799999,0.9060,4.998000,4.960,183.50,493.75,77.750000,775.0,73.099998,64.540001,0.008273
4,2000-09-06,274.200012,114.120003,5.712,20.790001,34.950001,0.9015,4.983000,5.065,186.25,493.75,77.750000,780.0,75.250000,64.360001,0.123456
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6449,2026-03-02,5294.399902,98.379997,4.048,21.440001,71.230003,5.8945,88.283997,2.960,433.25,1150.00,233.100006,2931.0,288.350006,62.590000,0.200640
6450,2026-03-03,5107.399902,99.050003,4.056,23.570000,74.559998,5.7735,82.922997,3.054,434.25,1155.75,234.125000,2925.0,286.950012,62.040001,0.453567
6451,2026-03-04,5120.200195,98.769997,4.080,21.150000,74.660004,5.8550,82.633003,2.917,431.75,1154.50,238.350006,2968.0,290.700012,62.160000,0.166204
6452,2026-03-05,5065.299805,99.320000,4.146,23.750000,81.010002,5.7530,81.686996,3.003,441.50,1163.75,238.524994,2963.0,293.000000,63.029999,0.474941
6453,2026-03-06,5158.700195,98.855003,4.133,29.490000,90.900002,5.8070,84.310997,3.186,460.50,1200.75,234.574997,3138.0,297.600006,64.300003,1.156538

### We observe that there are some rows where gold_yf populates but DXY, TNX, VIX don't, we neeed to forward fill these values so that the last known value is still in place.,

In [36]:
merged_df.fillna(method="ffill", inplace=True)

C:\Users\Sanket Lalwani\AppData\Local\Temp\ipykernel_13728\1686597910.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  merged_df.fillna(method="ffill", inplace=True)

In [37]:
merged_df.isna().sum()

Index
Date       0
Gold_YF    0
DXY        0
TNX        0
VIX        0
CrdOil     0
Cu         0
Ag         0
NatGas     0
Corn       0
Soya       0
Cattle     0
Coco       0
Coffee     0
Cotton     0
VIX_PCE    0
dtype: int64

In [38]:
merged_df["Gold_return_1d"] = merged_df["Gold_YF"].pct_change()

In [39]:
merged_df

Index,Date,Gold_YF,DXY,TNX,VIX,CrdOil,Cu,Ag,NatGas,Corn,Soya,Cattle,Coco,Coffee,Cotton,VIX_PCE,Gold_return_1d
0,2000-08-30,273.899994,112.139999,5.800,17.690001,33.400002,0.8850,4.930000,4.805,181.50,493.75,77.750000,760.0,73.900002,64.750000,-0.244654,NaN
1,2000-08-31,278.299988,112.599998,5.729,16.840000,33.099998,0.8850,5.003000,4.780,182.00,493.75,77.750000,745.0,74.500000,63.369999,-0.345588,0.016064
2,2000-09-01,277.000000,111.419998,5.675,17.530001,33.380001,0.8890,5.004000,4.835,183.25,493.75,77.750000,757.0,75.000000,63.490002,-0.263653,-0.004671
3,2000-09-05,275.799988,112.410004,5.683,19.820000,33.799999,0.9060,4.998000,4.960,183.50,493.75,77.750000,775.0,73.099998,64.540001,0.008273,-0.004332
4,2000-09-06,274.200012,114.120003,5.712,20.790001,34.950001,0.9015,4.983000,5.065,186.25,493.75,77.750000,780.0,75.250000,64.360001,0.123456,-0.005801
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6449,2026-03-02,5294.399902,98.379997,4.048,21.440001,71.230003,5.8945,88.283997,2.960,433.25,1150.00,233.100006,2931.0,288.350006,62.590000,0.200640,0.012217
6450,2026-03-03,5107.399902,99.050003,4.056,23.570000,74.559998,5.7735,82.922997,3.054,434.25,1155.75,234.125000,2925.0,286.950012,62.040001,0.453567,-0.035320
6451,2026-03-04,5120.200195,98.769997,4.080,21.150000,74.660004,5.8550,82.633003,2.917,431.75,1154.50,238.350006,2968.0,290.700012,62.160000,0.166204,0.002506
6452,2026-03-05,5065.299805,99.320000,4.146,23.750000,81.010002,5.7530,81.686996,3.003,441.50,1163.75,238.524994,2963.0,293.000000,63.029999,0.474941,-0.010722
6453,2026-03-06,5158.700195,98.855003,4.133,29.490000,90.900002,5.8070,84.310997,3.186,460.50,1200.75,234.574997,3138.0,297.600006,64.300003,1.156538,0.018439

In [40]:
merged_df["Gold_YF"].shift(5)[:10]

0           NaN
1           NaN
2           NaN
3           NaN
4           NaN
5    273.899994
6    278.299988
7    277.000000
8    275.799988
9    274.200012
Name: Gold_YF, dtype: float64

In [41]:
merged_df["Gold_forward_5d"] = ((merged_df["Gold_YF"].shift(-5) - merged_df["Gold_YF"])/merged_df["Gold_YF"])

In [42]:
merged_df

Index,Date,Gold_YF,DXY,TNX,VIX,CrdOil,Cu,Ag,NatGas,Corn,Soya,Cattle,Coco,Coffee,Cotton,VIX_PCE,Gold_return_1d,Gold_forward_5d
0,2000-08-30,273.899994,112.139999,5.800,17.690001,33.400002,0.8850,4.930000,4.805,181.50,493.75,77.750000,760.0,73.900002,64.750000,-0.244654,NaN,0.000365
1,2000-08-31,278.299988,112.599998,5.729,16.840000,33.099998,0.8850,5.003000,4.780,182.00,493.75,77.750000,745.0,74.500000,63.369999,-0.345588,0.016064,-0.017966
2,2000-09-01,277.000000,111.419998,5.675,17.530001,33.380001,0.8890,5.004000,4.835,183.25,493.75,77.750000,757.0,75.000000,63.490002,-0.263653,-0.004671,-0.014079
3,2000-09-05,275.799988,112.410004,5.683,19.820000,33.799999,0.9060,4.998000,4.960,183.50,493.75,77.750000,775.0,73.099998,64.540001,0.008273,-0.004332,-0.010515
4,2000-09-06,274.200012,114.120003,5.712,20.790001,34.950001,0.9015,4.983000,5.065,186.25,493.75,77.750000,780.0,75.250000,64.360001,0.123456,-0.005801,-0.005106
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6449,2026-03-02,5294.399902,98.379997,4.048,21.440001,71.230003,5.8945,88.283997,2.960,433.25,1150.00,233.100006,2931.0,288.350006,62.590000,0.200640,0.012217,NaN
6450,2026-03-03,5107.399902,99.050003,4.056,23.570000,74.559998,5.7735,82.922997,3.054,434.25,1155.75,234.125000,2925.0,286.950012,62.040001,0.453567,-0.035320,NaN
6451,2026-03-04,5120.200195,98.769997,4.080,21.150000,74.660004,5.8550,82.633003,2.917,431.75,1154.50,238.350006,2968.0,290.700012,62.160000,0.166204,0.002506,NaN
6452,2026-03-05,5065.299805,99.320000,4.146,23.750000,81.010002,5.7530,81.686996,3.003,441.50,1163.75,238.524994,2963.0,293.000000,63.029999,0.474941,-0.010722,NaN
6453,2026-03-06,5158.700195,98.855003,4.133,29.490000,90.900002,5.8070,84.310997,3.186,460.50,1200.75,234.574997,3138.0,297.600006,64.300003,1.156538,0.018439,NaN

In [43]:
import numpy as np
prices = merged_df["Gold_YF"].values
forward_5d = (prices[5:] - prices[:-5]) / prices[:-5]
merged_df["new_test_5dF"] = np.nan

In [44]:
merged_df.loc[merged_df.index[:len(forward_5d)], "new_test_5dF"] = forward_5d

In [45]:
merged_df[5500:6000]

Index,Date,Gold_YF,DXY,TNX,VIX,CrdOil,Cu,Ag,NatGas,Corn,Soya,Cattle,Coco,Coffee,Cotton,VIX_PCE,Gold_return_1d,Gold_forward_5d,new_test_5dF
5500,2022-05-23,1847.800049,102.080002,2.859,28.480000,110.290001,4.3475,21.723000,8.744,786.25,1687.00,132.774994,2451.0,215.750000,142.750000,1.036605,0.003258,-0.002760,-0.002760
5501,2022-05-24,1865.099976,101.860001,2.760,29.450001,109.769997,4.3255,22.063000,8.796,771.75,1693.00,132.725006,2441.0,213.649994,141.539993,1.151788,0.009362,-0.011688,-0.011688
5502,2022-05-25,1846.199951,102.059998,2.749,28.370001,110.330002,4.2770,21.860001,8.971,772.25,1681.00,132.300003,2407.0,217.050003,145.160004,1.023544,-0.010134,0.010996,0.010996
5503,2022-05-26,1847.400024,101.830002,2.756,27.500000,114.089996,4.2550,21.941000,8.908,765.00,1726.50,132.399994,2464.0,226.600006,140.610001,0.920235,0.000650,-0.001083,-0.001083
5504,2022-05-27,1851.300049,101.669998,2.743,25.719999,115.070000,4.3040,22.059999,8.727,777.25,1732.25,132.175003,2462.0,229.449997,139.419998,0.708869,0.002111,-0.006536,-0.006536
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,2024-05-10,2367.300049,105.309998,4.504,12.550000,78.260002,4.6935,28.275000,2.252,455.75,1205.00,176.149994,9874.0,204.399994,77.309998,-0.855004,0.015094,0.018967,0.018967
5996,2024-05-13,2336.100098,105.220001,4.481,13.600000,79.120003,4.8045,28.221001,2.381,458.50,1205.50,175.574997,8149.0,200.399994,77.629997,-0.730322,-0.013180,0.041865,0.041865
5997,2024-05-14,2353.399902,105.010002,4.445,13.420000,78.019997,4.9535,28.485001,2.344,453.75,1199.00,178.175003,8751.0,202.850006,74.629997,-0.751696,0.007405,0.029022,0.029022
5998,2024-05-15,2388.699951,104.349998,4.356,12.450000,78.629997,4.9695,29.514000,2.416,462.50,1213.50,178.250000,9066.0,201.250000,75.410004,-0.866879,0.015000,0.000209,0.000209
5999,2024-05-16,2380.000000,104.459999,4.377,12.420000,79.230003,4.8920,29.665001,2.495,457.00,1216.25,179.024994,7393.0,199.550003,76.239998,-0.870441,-0.003642,-0.018908,-0.018908

In [46]:
def target(x):
    if x >= 0.02:
        return 1
    elif x <= -0.02:
        return -1
    else:
        return 0

In [47]:
merged_df["Target"] = merged_df["Gold_forward_5d"].apply(target)

In [48]:
merged_df["Target"].value_counts(normalize=True)

Target
 0    0.646111
 1    0.206848
-1    0.147041
Name: proportion, dtype: float64

In [49]:
# Easier Method
merged_df["Target"] = 0
merged_df.loc[merged_df["Gold_forward_5d"] >= 0.02, "Target"] = 1
merged_df.loc[merged_df["Gold_forward_5d"] <= -0.02, "Target"] = -1

In [50]:
merged_df

Index,Date,Gold_YF,DXY,TNX,VIX,CrdOil,Cu,Ag,NatGas,Corn,Soya,Cattle,Coco,Coffee,Cotton,VIX_PCE,Gold_return_1d,Gold_forward_5d,new_test_5dF,Target
0,2000-08-30,273.899994,112.139999,5.800,17.690001,33.400002,0.8850,4.930000,4.805,181.50,493.75,77.750000,760.0,73.900002,64.750000,-0.244654,NaN,0.000365,0.000365,0
1,2000-08-31,278.299988,112.599998,5.729,16.840000,33.099998,0.8850,5.003000,4.780,182.00,493.75,77.750000,745.0,74.500000,63.369999,-0.345588,0.016064,-0.017966,-0.017966,0
2,2000-09-01,277.000000,111.419998,5.675,17.530001,33.380001,0.8890,5.004000,4.835,183.25,493.75,77.750000,757.0,75.000000,63.490002,-0.263653,-0.004671,-0.014079,-0.014079,0
3,2000-09-05,275.799988,112.410004,5.683,19.820000,33.799999,0.9060,4.998000,4.960,183.50,493.75,77.750000,775.0,73.099998,64.540001,0.008273,-0.004332,-0.010515,-0.010515,0
4,2000-09-06,274.200012,114.120003,5.712,20.790001,34.950001,0.9015,4.983000,5.065,186.25,493.75,77.750000,780.0,75.250000,64.360001,0.123456,-0.005801,-0.005106,-0.005106,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6449,2026-03-02,5294.399902,98.379997,4.048,21.440001,71.230003,5.8945,88.283997,2.960,433.25,1150.00,233.100006,2931.0,288.350006,62.590000,0.200640,0.012217,NaN,NaN,0
6450,2026-03-03,5107.399902,99.050003,4.056,23.570000,74.559998,5.7735,82.922997,3.054,434.25,1155.75,234.125000,2925.0,286.950012,62.040001,0.453567,-0.035320,NaN,NaN,0
6451,2026-03-04,5120.200195,98.769997,4.080,21.150000,74.660004,5.8550,82.633003,2.917,431.75,1154.50,238.350006,2968.0,290.700012,62.160000,0.166204,0.002506,NaN,NaN,0
6452,2026-03-05,5065.299805,99.320000,4.146,23.750000,81.010002,5.7530,81.686996,3.003,441.50,1163.75,238.524994,2963.0,293.000000,63.029999,0.474941,-0.010722,NaN,NaN,0
6453,2026-03-06,5158.700195,98.855003,4.133,29.490000,90.900002,5.8070,84.310997,3.186,460.50,1200.75,234.574997,3138.0,297.600006,64.300003,1.156538,0.018439,NaN,NaN,0

### Try: Option 2 — Volatility-Adjusted Threshold (Advanced)

In [51]:
merged_df["Target_1.5"] = 0
merged_df.loc[merged_df["Gold_forward_5d"] >= 0.015, "Target_1.5"] = 1
merged_df.loc[merged_df["Gold_forward_5d"] <= -0.015, "Target_1.5"] = -1

In [52]:
merged_df["Target_1.5"].value_counts(normalize=True)

Target_1.5
 0    0.517663
 1    0.277347
-1    0.204989
Name: proportion, dtype: float64

In [53]:
merged_df["Gold_forward_5d"].quantile([0.7, 0.75, 0.8, 0.85, 0.9])

0.70    0.013591
0.75    0.016830
0.80    0.020444
0.85    0.024857
0.90    0.030130
Name: Gold_forward_5d, dtype: float64